### ISSUE TITLE
record MIDI?

### ISSUE THREAD

**Issue by naught101** [op1hacks/op1repacker#15]
Any idea if there would be any way to record MIDI from the keyboard while recording audio? If it were possible to capture that data and then copy it off the OP-1 when copy the tape tracks, that would make it much nice to manipulate and augment the audio in a DAW..

**Comment by richrd** [comment]
I don't think we can make a mod for that. However you could record midi into some other device while recording to tape. Maybe not a very portable solution but I can't think of anything else. A DAW would work for that. Or maybe an iPhone or Android MIDI app.
