### ISSUE TITLE
Stuck on that 0.1.1

### ISSUE THREAD

**Issue by L33t-HAXXOR** [op1hacks/op1repacker#19]
Python3 version 3.4.8
MacOS 10.13.4
Pip version 10.0.1

I have no clue how to update to 0.1.4

**Comment by L33t-HAXXOR** [comment]
Issue fixed! 
Simply run:

`sudo pip3 uninstall op1repacker`

to uninstall the utility.

Then run:

`sudo pip3 install op1repacker`

to update to the newest version! ＼(＾▽＾)／

They don’t call me L33T-HAXXOR fer nuthin’.

**Comment by bitcoin4cashqc** [comment]
What's new in the 0.1.4 version?

**Comment by DurtiCurti** [comment]
Didnt think it was a monor update. Worth it? Or just wanting to run the code

**Comment by bitcoin4cashqc** [comment]
Eh what do you mean

**Comment by DurtiCurti** [comment]
Comment updated

**Comment by L33t-HAXXOR** [comment]
0.1.4 comes with:
Tape screen invert for easy couch visibility
Iter-lab (graphics for Iter synth)
Mwose (Moose replaces Cow in CWO effect)
Among other things

**Comment by bitcoin4cashqc** [comment]
But all theses was already there right

**Comment by DurtiCurti** [comment]
Already have all this, guess why I wasnt interested

**Comment by richrd** [comment]
@L33t-HAXXOR Good that you found a way to do it! For future reference the simplest method is `sudo pip3 install op1repacker --upgrade`
