### ISSUE TITLE
Do you think it's possible to add custom (micro)tuning?

### ISSUE THREAD

**Issue by gexahedron** [op1hacks/op1repacker#20]
Do you think it's possible to add custom (micro)tuning (pitch shifting) to each note? Not just global detuning, but each note would receive it's own detune.

**Comment by richrd** [comment]
No, unfortunately not possible. We're unable to change the behavior of the firmware since we haven't been able to modify the actual firmware code.

**Comment by DurtiCurti** [comment]
Actually people dont want to invest in breaking down the code because of the time, and because they dont want to offend TE. Thats been picked at long ago, and everyone is too affraid/busy/or bosie to risk bricking the op-1. That being said, get it another 10 years lol

**Comment by richrd** [comment]
Pretty much like @DurtiCurti said. It's a major undertaking and no matter how much time is spent success isn't guaranteed. I don't want to offend TE but if I had the skills and time to reverse engineer the code I'd probably try to do that. Anyway without the original source code mods like this are really hard if not impossible.

PS. @DurtiCurti Wow, we have the same avatar except it's flipped :)
