### ISSUE TITLE
op-z unpack?

### ISSUE THREAD

**Issue by devn** [op1hacks/op1repacker#21]
I attempted to unpack the op-z firmware by removing the first 4 bytes and unpacking with lzma, but something has changed. I'm not sure if the CRC has changed, or whether it's a different compression format. Any tips on how to comb headers to determine the type?

Thanks in advance!

**Comment by devn** [comment]
Unfortunately, it looks like this is going to be a tough one to figure out. I believe TobascoEye (is this you, by any chance?) in the thread [here](https://op-forums.com/t/op-z-firmware-updates/7677/9) is correct, the op-z firmware that TE distributes is encrypted. 

I've read over all of the docs at https://www.analog.com/en/products/adsp-bf703.html#product-documentation, and nothing sticks out on my first read, however, I think that the OP-Z's bluetooth LE connection, and upcoming modules may provide an opportunity to retrieve the PK from the device or otherwise dump firmware.

**Comment by richrd** [comment]
Hi! I haven't looked into the OP-Z firmware yet, so I can't really say anything. And no, I'm not TabascoEye :) I'm wavi on the forums. TabascoEye has more firmware skills than I so he might be able to figure something out!

**Comment by richrd** [comment]
If the OP-Z firmware is successfully unpacked, it'll probably make the most sense to write a separate tool to handle that, so I'm closing this for now.
