### ISSUE TITLE
Compatible with OS 235?

### ISSUE THREAD

**Issue by yamamushi** [op1hacks/op1repacker#22]
A new OP-1 firmware is available, and I'm wondering if this is compatible with it, or there are plans to update it to keep it compatible?

https://teenageengineering.com/downloads/op-1

**Comment by DurtiCurti** [comment]
I’m wondering the same

**Comment by jfrey-xx** [comment]
I used the op1repacker to patch this firmware, activated all options but "subtle-fx", everything worked as usual. Someone else on https://op-forums.com/t/custom-firmware-on-the-op-1/4283/663 tried to enable everything but the moose, so I'd say it's compatible :)

**Comment by rssk** [comment]
I'm having issues w/ iter appearing on 235 at the moment, but everything else seems fine

**Comment by richrd** [comment]
I love how there's already been discussion here even before I notice the issue. Anyway the actual unpacking and repacking should be compatible with all firmware versions, but the mods might not work on future firmware. I haven't tested the latest FW yet but judging by the reports, everything should work fine.

**Comment by DurtiCurti** [comment]
I just ipgraded custome firware 235 only mods i didn't do was the moose nore the iter fx. Other than that everything works, and went smoothly

**Comment by rosshardy** [comment]
I tried all mods except for lab gfx. All worked, including moose!

**Comment by richrd** [comment]
I also tested all mods and can confirm everything is compatible with OS 235
