### ISSUE TITLE
All mods option outputs too large of a file to use

### ISSUE THREAD

**Issue by JosefSaltz** [op1hacks/op1repacker#27]
I assumed since it's listed in the readme that you can enable all mods that you should get a usable firmware file when doing so. I'm modifying the op1_235.op1 firmware and trying to enable all included mods but receive a 24Mb file that is too large to use on the OP-1.

**Comment by richrd** [comment]
I always go with all the mods and the latest firmware (235) and haven't had any size issues. The mod's don't actually add a lot of data to the firmware, so I suspect it must be some issue with the compression parameters, for some reason LZMA compression can behave differently on some platforms.

Could you let me know what OS you are running op1repacker on, and what python version you have?

**Comment by JosefSaltz** [comment]
Okay that's interesting. I'm running it on Windows 10 WSL using Python 3.7.4

**Comment by richrd** [comment]
That's very weird, I've never had or heard of anyone else having that kind of issue. I hope reinstalling the stock firmware or a factory reset (or both) help, usually they do. It sounds like some recursive stuff is happening in your repacking process. 

Could you post the exact commands you're using, the order of them, and which op1repacker version you have?
You can check the op1repacker version by running `op1repacker -v`. If you don't have version 0.2.2 then try that and see what size of modified firmware it gives you.

**Comment by richrd** [comment]
I found out that this is a bug with op1repacker, and it happens when specifying the directory with a slash at the end e.g. `op1_235/` instead of without the slash `op1_235`.

The bug causes op1repacker to repack the parent directory instead of the specified one. That results in invalid firmware files but luckily they won't brick the OP-1 even if you try to install them.

**Comment by richrd** [comment]
So basically the issue wasn't enabling all the mods. Instead it was caused by repacking the directory with a slash at the end which caused building the parent directory instead of the specified firmware directory.

This has been fixed in version 0.2.3.
