### ISSUE TITLE
Compatibility with 241

### ISSUE THREAD

**Issue by PloxKevin** [op1hacks/op1repacker#30]
Tested to be compatible with 241. Played an hour with it and seem to not have any issues.

**Comment by DurtiCurti** [comment]
Glad to know this

**Comment by DurtiCurti** [comment]
I’ll test it tonight with, everything, but Iter_FX and moose effect active

**Comment by richrd** [comment]
Thanks! I'm curious to know which python version you are using 3.6, 3.7 or 3.8 ? Some people seem to have some issues building installable firmware files on some versions.

**Comment by DurtiCurti** [comment]
It works. I’ll check my python version when I get home

**Comment by PloxKevin** [comment]
Used 3.7 to repack.
